### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Arsonide** [Earu/gm_animalese#3]
Hey Earu,

I'm working on a [very similar mod](https://github.com/Arsonide/Babbler) for the game "Shadows of Doubt". It makes the citizens "babble" like Animal Crossing. I've been searching around for sound samples for the babble, and I like the 8 vocal variants you set up here...but I can't use them because this repository has no license.

Do you think you could add one? I'm happy to attribute in whatever way you want. I've also reached out on Steam and Discord.

**Comment by Earu** [comment]
Hey there, here you go https://github.com/Earu/gm_animalese/commit/906c10a409f74857ecb1f8f334247b1f13d7b199

Credits would be appreciated, but do not feel obligated.

**Comment by Arsonide** [comment]
Awesome, thanks!
